development:
  adapter: sqlite3
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  username: rails
  password: ENV['APP_DATABASE_PASSWORD']
  pool: 5
  timeout: 5000